bilateral_teleop:
  ros__parameters:
    kp:                5.0
    max_vel:           2.5
    max_accel:         5.0
    alpha_vel:         0.20
    force_threshold:   3900
    force_hysteresis:  3950
    calib_samples:     80
    calib_std_max:     0.02
    watchdog_timeout:  0.5
    torque_gain:       0.15
force_stop_node:
  ros__parameters:
    force_threshold:   3900
master_teleop:
  ros__parameters:
    torque_scale:      1.0
